name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      if: github.event_name == 'push'
      run: npm run build
      env:
        OLLAMA_API_URL: ${{ secrets.OLLAMA_API_URL }}
        OLLAMA_DEFAULT_MODEL: ${{ secrets.OLLAMA_DEFAULT_MODEL }}

    - name: Build (PR)
      if: github.event_name == 'pull_request'
      run: npm run build
